version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: thesis_postgres
    ports:
      - "5432:5432" # Exposes PostgreSQL on localhost:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: thesis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
